export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_BAGS: "SET_BAGS",
  SET_JEWELRY: "SET_JEWELRY",
  SET_SHOES: "SET_SHOES",
  // SELECTED_PRODUCT: "SELECTED_PRODUCT",
  //   REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
