export const ActionTypes = {
  GET_PRODUCTS_REQUEST: "GET_PRODUCTS_REQUEST",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_FAILURE: "GET_PRODUCTS_FAILURE",

  GET_BAGS_REQUEST: "GET_BAGS_REQUEST",
  GET_BAGS_SUCCESS: "GET_BAGS_SUCCESS",
  GET_BAGS_FAILURE: "GET_BAGS_FAILURE",

  GET_JEWELRY_REQUEST: "GET_JEWELRY_REQUEST",
  GET_JEWELRY_SUCCESS: "GET_JEWELRY_SUCCESS",
  GET_JEWELRY_FAILURE: "GET_JEWELRY_FAILURE",

  GET_SHOES_REQUEST: "GET_SHOES_REQUEST",
  GET_SHOES_SUCCESS: "GET_SHOES_SUCCESS",
  GET_SHOES_FAILURE: "GET_SHOES_FAILURE",

  // SELECTED_PRODUCT: "SELECTED_PRODUCT",

  // SET_PRODUCTS_FILTERED: "SET_PRODUCTS_FILTERED",
  //   REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
